"""Add destinataire field to Address table

Revision ID: 079f4604893e
Revises: e56aa28c608b
Create Date: 2025-04-07 19:37:03.446246

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "079f4604893e"
down_revision: Union[str, None] = "e56aa28c608b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "addresses", sa.Column("recipient", sa.String(length=255), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("addresses", "recipient")
    # ### end Alembic commands ###
