"""create_reviews_system

Revision ID: 0fef0773543b
Revises: 7ccb7d2db203
Create Date: 2025-06-26 18:44:48.266654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fef0773543b'
down_revision: Union[str, None] = '7ccb7d2db203'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('rating', sa.Integer(), nullable=False))
    op.add_column('notes', sa.Column('comment', sa.Text(), nullable=True))
    op.add_column('notes', sa.Column('seller_id', sa.Integer(), nullable=False))
    op.add_column('notes', sa.Column('reviewer_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'notes', ['annonce_id'])
    op.drop_constraint(op.f('notes_user_id_fkey'), 'notes', type_='foreignkey')
    op.create_foreign_key(None, 'notes', 'users', ['reviewer_id'], ['id'])
    op.create_foreign_key(None, 'notes', 'users', ['seller_id'], ['id'])
    op.drop_column('notes', 'value')
    op.drop_column('notes', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('notes', sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.create_foreign_key(op.f('notes_user_id_fkey'), 'notes', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'notes', type_='unique')
    op.drop_column('notes', 'reviewer_id')
    op.drop_column('notes', 'seller_id')
    op.drop_column('notes', 'comment')
    op.drop_column('notes', 'rating')
    # ### end Alembic commands ###
