"""Add foreign key constraint for last_message_id

Revision ID: 41194be7b9db
Revises: c2750fc93b1e
Create Date: 2025-08-17 16:12:33.269351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41194be7b9db'
down_revision: Union[str, None] = 'c2750fc93b1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'conversations', 'messages', ['last_message_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    # ### end Alembic commands ###
