"""add_nullable_to_signature

Revision ID: 428dd288a194
Revises: 0fef0773543b
Create Date: 2025-06-28 15:39:40.938714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '428dd288a194'
down_revision: Union[str, None] = '0fef0773543b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_requests', sa.Column('signature', sa.String(), nullable=True))
    op.drop_column('price_requests', 'message')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_requests', sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('price_requests', 'signature')
    # ### end Alembic commands ###
