"""Replace address_id with address JSON field

Revision ID: 4a0c8d007287
Revises: a516a048a49e
Create Date: 2025-04-15 08:58:08.899293

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4a0c8d007287"
down_revision: Union[str, None] = "a516a048a49e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("annonces", sa.Column("address", sa.JSON(), nullable=True))
    op.drop_constraint("annonces_address_id_fkey", "annonces", type_="foreignkey")
    op.drop_column("annonces", "address_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "annonces",
        sa.Column("address_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "annonces_address_id_fkey", "annonces", "addresses", ["address_id"], ["id"]
    )
    op.drop_column("annonces", "address")
    # ### end Alembic commands ###
