"""Add email field to User table

Revision ID: 6e93cb2cdd47
Revises: 67b3161dd80b
Create Date: 2025-04-18 21:22:26.878022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e93cb2cdd47'
down_revision: Union[str, None] = '67b3161dd80b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('email_otp', sa.String(length=6), nullable=True))
    op.add_column('users', sa.Column('email_otp_created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_otp_created_at')
    op.drop_column('users', 'email_otp')
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
