"""Add status field to Annonce table

Revision ID: 7117c09afe28
Revises: 2bcca69c971d
Create Date: 2025-04-09 14:04:53.854785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7117c09afe28'
down_revision: Union[str, None] = '2bcca69c971d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annonces', sa.Column('status', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('annonces', 'status')
    # ### end Alembic commands ###
