"""add temporary ban to users

Revision ID: 7ccb7d2db203
Revises: bb1ab1d4e29a
Create Date: 2025-06-26 11:22:17.768169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ccb7d2db203'
down_revision: Union[str, None] = 'bb1ab1d4e29a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_banned', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('users', sa.Column('ban_expires_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('ban_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ban_reason')
    op.drop_column('users', 'ban_expires_at')
    op.drop_column('users', 'is_banned')
    # ### end Alembic commands ###
