"""Add GlobalSetting table

Revision ID: a516a048a49e
Revises: be14b71b9779
Create Date: 2025-04-14 15:11:19.705238

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a516a048a49e"
down_revision: Union[str, None] = "be14b71b9779"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "global_settings",
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("last_annonce_index_on_chain", sa.Integer(), nullable=False),
        sa.CheckConstraint("id = 1", name="single_row_check"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("global_settings")
    # ### end Alembic commands ###
