"""add shipping_regions to annonces

Revision ID: bb1ab1d4e29a
Revises: 5ff82d56f60e
Create Date: 2025-06-25 22:05:45.522594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb1ab1d4e29a'
down_revision: Union[str, None] = '5ff82d56f60e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annonces', sa.Column('shipping_regions', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('annonces', 'shipping_regions')
    # ### end Alembic commands ###
