"""Add user_id foreign key to Annonce table

Revision ID: bce8fbd1952d
Revises: 8d02ebc7755d
Create Date: 2025-03-24 12:02:57.232490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bce8fbd1952d'
down_revision: Union[str, None] = '8d02ebc7755d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annonces', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'annonces', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'annonces', type_='foreignkey')
    op.drop_column('annonces', 'user_id')
    # ### end Alembic commands ###
