"""Add pubkey field to Annonce table

Revision ID: be14b71b9779
Revises: 3bbfccff7654
Create Date: 2025-04-14 14:37:44.531718

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "be14b71b9779"
down_revision: Union[str, None] = "3bbfccff7654"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("annonces", sa.Column("pubkey", sa.String(length=44), nullable=True))
    op.create_unique_constraint(None, "annonces", ["pubkey"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "annonces", type_="unique")
    op.drop_column("annonces", "pubkey")
    # ### end Alembic commands ###
