"""Add conversation and notification tables

Revision ID: c2750fc93b1e
Revises: cdff1d5ce38e
Create Date: 2025-08-17 16:11:13.643701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2750fc93b1e'
down_revision: Union[str, None] = 'cdff1d5ce38e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('action_url', sa.String(length=500), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('sent_via', sa.JSON(), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notifications_created', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_notifications_priority', 'notifications', ['priority'], unique=False)
    op.create_index('idx_notifications_type', 'notifications', ['notification_type'], unique=False)
    op.create_index('idx_notifications_user_unread', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('annonce_id', sa.Integer(), nullable=True),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('last_message_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('archived_by', sa.Integer(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['annonce_id'], ['annonces.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['archived_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conversations_active', 'conversations', ['is_active', 'is_archived'], unique=False)
    op.create_index('idx_conversations_annonce', 'conversations', ['annonce_id'], unique=False)
    op.create_index('idx_conversations_last_message', 'conversations', ['last_message_at'], unique=False)
    op.create_index('idx_conversations_users', 'conversations', ['buyer_id', 'seller_id'], unique=False)
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=20), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('read_by', sa.JSON(), nullable=True),
    sa.Column('message_metadata', sa.JSON(), nullable=True),
    sa.Column('reply_to_id', sa.Integer(), nullable=True),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('is_edited', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reply_to_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_messages_conversation_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index('idx_messages_sender', 'messages', ['sender_id'], unique=False)
    op.create_index('idx_messages_unread', 'messages', ['conversation_id', 'is_read'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_table('user_conversation_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('last_read_message_id', sa.Integer(), nullable=True),
    sa.Column('unread_count', sa.Integer(), nullable=True),
    sa.Column('is_muted', sa.Boolean(), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(), nullable=True),
    sa.Column('notification_preferences', sa.JSON(), nullable=True),
    sa.Column('custom_name', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_read_message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'conversation_id', name='uq_user_conversation_status')
    )
    op.create_index('idx_user_conversation_status_activity', 'user_conversation_status', ['user_id', 'last_activity_at'], unique=False)
    op.create_index('idx_user_conversation_status_conversation', 'user_conversation_status', ['conversation_id'], unique=False)
    op.create_index('idx_user_conversation_status_unread', 'user_conversation_status', ['user_id', 'unread_count'], unique=False)
    op.create_index('idx_user_conversation_status_user', 'user_conversation_status', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_conversation_status_id'), 'user_conversation_status', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_conversation_status_id'), table_name='user_conversation_status')
    op.drop_index('idx_user_conversation_status_user', table_name='user_conversation_status')
    op.drop_index('idx_user_conversation_status_unread', table_name='user_conversation_status')
    op.drop_index('idx_user_conversation_status_conversation', table_name='user_conversation_status')
    op.drop_index('idx_user_conversation_status_activity', table_name='user_conversation_status')
    op.drop_table('user_conversation_status')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index('idx_messages_unread', table_name='messages')
    op.drop_index('idx_messages_sender', table_name='messages')
    op.drop_index('idx_messages_conversation_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_index('idx_conversations_users', table_name='conversations')
    op.drop_index('idx_conversations_last_message', table_name='conversations')
    op.drop_index('idx_conversations_annonce', table_name='conversations')
    op.drop_index('idx_conversations_active', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index('idx_notifications_user_unread', table_name='notifications')
    op.drop_index('idx_notifications_type', table_name='notifications')
    op.drop_index('idx_notifications_priority', table_name='notifications')
    op.drop_index('idx_notifications_created', table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
