"""add timestamp to price_requests

Revision ID: cdff1d5ce38e
Revises: 3d5f37700e0a
Create Date: 2025-07-08 17:10:55.346662

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cdff1d5ce38e'
down_revision: Union[str, None] = '3d5f37700e0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_requests', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price_requests', 'timestamp')
    # ### end Alembic commands ###
