"""Add address

Revision ID: e56aa28c608b
Revises: bce8fbd1952d
Create Date: 2025-04-03 18:09:46.002761

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e56aa28c608b"
down_revision: Union[str, None] = "bce8fbd1952d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "addresses",
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("address", sa.String(length=255), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("postal_code", sa.String(length=20), nullable=False),
        sa.Column("country", sa.String(length=100), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_user_default_address",
        "addresses",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("is_default = true"),
    )
    op.add_column("annonces", sa.Column("address_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "annonces", "addresses", ["address_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "annonces", type_="foreignkey")
    op.drop_column("annonces", "address_id")
    op.drop_index(
        "uq_user_default_address",
        table_name="addresses",
        postgresql_where=sa.text("is_default = true"),
    )
    op.drop_table("addresses")
    # ### end Alembic commands ###
